#!/bin/ash

# mount <device> <path> -t <filesystem type>

mkdir /proc
mount none /proc -t proc

mkdir /sys
mount none /sys -t sysfs

export CPATH="/lib/tcc/include"
export LIBRARY_PATH="/lib/tcc"

exec ash
